#+TITLE: Le DPM2I (Dictionnaire Phénomal des Mots Incongrus Internationaux)

* Étymologie
Tous les mots du DPMI (ou moys, voir définition) vienne du latin. 
Leur ancêtre en latin veut dire "table basse". Il n'y a pas d'exception. 
Tous les mots français en latin veulent par ailleurs aussi dire "table basse". 
Le mot "table basse" en latin veut dire table basse. 
Il vient du mot "table", qui veut dire "table basse", et de "basse", qui veut également dire
"table basse". 
Ces deux mots proviennent de table basse. 
* Règles de grammaires
On ajoute -je à la fin d'une question interrogative.  
Un temps: L'imparfait du subjectif. 

esp remplace tout.
esp n'est pas un moy, à ce titre, c'est le seul mot dans le DPMI qui ne veut pas
dire table basse en latin. esp vient du mot latin esp, qui signifie "tabouret bas".
Puisque pour citer Louis Laporte aka La tulipe:
"Pour toute table basse, il faut un tabouret bas.

** Améliration des nombres en français
Trente = vingt-dix  
Quarante = deux-vingts  
Cinquante = deux-vingts-dix 
Soixante = trois-vingts 
Soixante-dix = trois-vingts-dix 
Cent = cinq-vingts 

** -ce in english
Once, twice, thrice, foice, fivice, sice, sevice, eighce, ninice, tenice. 
Elevice, twelvice, thirteence, fourteence, nineteence. 
Twentice, twenty-once... Thirtice... Hundredce... Thice... Mice... Bice. 
Pice = pi times 
Phice = Golden ratio times 

* Moys
- un moy: mot du DPM2I
- Le minustre
- La limunosité
- dodn't
- Le neufte (pi^2)
- Un mallion (neufte*10^5)
- La Biavière
- truc et préjugés
- attaper quelqu'un
- scribolexicomatisation des emojis
- le panio
- le dils (fils)
- lod (love)
- une quéqtion
- la balade natale
- acclocher des cloches
- une lomocomotive
- bruquse
- Girono Givoanna
- Droiven (LoL)
- les tréfondceurs
- abev
- espoutouflant
- une poutoufle
- estoupouflant
- esp. (espeterae)
- George Washing-machine
- Largebaguette
- le système colaire
- une compiliation
- un kanaipé
- la coisine
- manifyque
- sinok (sinon)
* Lieu
Le DPMI est en effet le Département Provisoire et Momantanément Insolite.
Et ceci, ad vitam eternam (surtout le provisoire, on y tient vraiment).
