#+TITLE: Le DPM2I (Dictionnaire Phénomal des Mots Incongrus Internationaux)

* Étymologie
Tous les mots du DPMI (ou moys, voir définition) vienne du latin. 
Leur ancêtre en latin veut dire "table basse". Il n'y a pas d'exception. 

Tous les mots français en latin veulent par ailleurs aussi dire "table basse". 

+ *Ex:* Le mot "table basse" en latin veut dire table basse. 

Il vient du mot "table", qui veut dire "table basse", et de "basse", qui veut également dire
"table basse". 

Ces deux mots proviennent de table basse. 
* Règles de grammaire
On ajoute -je à la fin d'une question interrogative.  

Un temps: L'imparfait du subjectif. (je croivais)

esp remplace tout. 
esp n'est pas un moy, à ce titre, c'est le seul mot dans le DPMI qui ne veut pas
dire table basse en latin. 

esp vient du mot latin esp, qui signifie "tabouret bas".
Puisque pour citer Louis La tulipe aka Laporte:

"Pour toute table basse, il faut un tabouret bas."

** Améliration des nombres en français
- Trente = vingt-dix
- Quarante = deux-vingts  
- Cinquante = deux-vingts-dix 
- Soixante = trois-vingts 
- Soixante-dix = trois-vingts-dix 
- Cent = cinq-vingts 

** -ce in english
Once, twice, thrice, foice, fivice, sice, sevice, eighce, ninice, tenice. 

Elevice, twelvice, thirteence, fourteence, nineteence. 

Twentice, twenty-once... Thirtice... Hundredce... Thice... Mice... Bice. 

Pice = pi times 

Phice = Golden ratio times 

** Genre neutre
Genre qui a pour déterminant indéfini unk et défini lke, qui sont prononcés en verlan.
* Moys
** Grammoys
- un *moy:* mot du DPM2I
- un *grammoy:* moy parlant de la grammaire
- un *vebre:* moy qui est un verbe
- un *subvantif:* moy qui est un nom
- un *advectif:* moy qui est un adjectif
- un *advebre:* moy qui est un advebre
- une *vréposition:* moy qui est une préposition

** Le reste
- un *minustre:* ministre avec une pilosité extrêment prononcée. 
  + *Ex:* Ledru-Rollin
- une *limunosité:* luminosité d'origine organique.
- I dod or I dodn't: équivalent de si ou di après une question négative en anglais.
- le *neufte:* nombre qui a pour valeur pi au carré. Ex: j'ai acheté neufte pommes hier.
- Un *mallion:* million qui se sent mal, car il vaut seulement neufte*10^5.
- la *Biavière:* région du monde pas encore répertoriée, où se trouve le DPMI et 
    une population importante de tables basses et de tabourets bas. Habitant: Biavièrois(e).
    Elle se trouve entre les USA et le Japon, la France et la Chine, la Russie du Sud et la Russie du Nord, 
    entre l'Arctique et l'Antartique.
- *truc et préjugés:* livre du XVIème siècle av. JC écrit par Austen Jane. Truc subit préjugés. 
    3€30 dans toutes les librairies de la Biavière.
- *attaper:* attaquer physiquement quelqu'un, en le tapant par exemple. 
- une *scribolexicomatisation:* remplacment progressif du langage écrit.  
  + *Ex:* Les réseaux sociaux provoquent une certaine scribolexicomatisation des emojis.
- un *panio:* piano ne possédant plus de touches ré majeur, sur lequel on dépose un panier.
- un *dils:* fils ayant dix frères et soeurs.
- *lod:* être tellement amoureux qu'on en devient un caillou.  
  + *Ex:* 
        #+BEGIN_QUOTE
	J'aimerais être [...]
	juste une pierre sur son chemin.
	--- Maître Gims, /Bella/, 2013
        #+END_QUOTE
- une *quéqtion:* question interrogative (voir Règles de grammaire).
- la *balade natale:* fait de se promoner sur la carte de la bataille navale.
- *acclocher:* accrocher des cloches à une table basse.
- une *lomocomotive:* locomotive accédant à des lieux incongrus et non-répértoriés.
    A été inventée par George Washing-machine.  
  + *Ex:* x.
- *bruquse:* qui agit de manière skillée, stylée et brusque.  
  + *Ex:* Faker.
- *Girono Givoanna:* personnage principal de la partie 5 de JiJi's Bizarre Adventure: Gilden Wind.
- *Droiven:* personnage de Leoigue of Legends, qui est un tireur spécialisé en ragequit.
- des *tréfondceurs:* endroit profond qui regorge de limunosité. 
- *abev:* indique le fait d'être muni de moins ce que l'on avait prévu. Synonyme de "seulement avec".
- une *poutoufle:* pantoufle coupant le souffle.
- *espoutoufler:* provoquer un sentiment de poutoufle général. (espoutouflant)  
  + *Ex:* Après sa blague, le public fut espoutouflé.
- un *estoupouflan:* plat provoquant un manque de souffle prononcé. 
- *esp.:* lien entre un tabouret bas et une table basse.
- *George Washing-machine:* créateur de la lomocomotive.
- *Marquis de Largebaguette:* détenteur du magasin "Votre Large Baguette", 
    trouvable dans toutes les librairies de la Biavière.
- le *système colaire:* système stellaire présent dans le système digestif des Biavièrois.
- une *compiliation:* 
  1. compilation de compilation.
  2. décompilation d'un fichier en binaire en un fichier lisible par un humain.
- *tripafouiller:* tripoter en fouillant.  
  + *Ex:* J'ai malencontreusement tripafouiller un mur invisible.
- a *fraind:* personne extrêment lente qui freine ses amis.
- to *fraindzone:* être friendzone très lentement.
- un *kanaipé:* canapé qui fait office d'épée.
- une *coisine:* cuisine d'une vosine.
- *manifyque:* qui est plus magnifique que magnifique.
- *sinok:* introduit la négation d'une hypothèse évidente.
  * Ex: Manges ta soupe, sinok tu la digéreras.
- *à aujourd'hui dans plus tard:* expression utilisée très tôt le matin(0:00 à 4:00) comme substitut à "à demain".  
  + *Ex:*
        - À demain!  
        - Mais non il est 2 heures du matin!  
        - Ah! bah à aujourd'hui dans plus tard!
- un *doit:* toit en forme de doigt.
- *enpensionnér:* empoisonner une personne dans une pension.
- the *elbbump (ELBow BUMP):* salutation consistant à se tapoter les coudes de manière à respecter 
    l'hygiène pendant une épidémie.
- le *deuze:* nombre aussi mystérieux que la position de la Biavière.
- un *elasticot:* asticot elastique.
- *of sure:* expréssion de conscession évidente.
- *drunking:* fait de se bourrer. 
- *di:* marque la négation après une interrogation négative.
- *fik:* fin peu satisfaisante.
- *allimer:* dégager de la limunosité.
- *limunaire:* qui s'allime.
- *équolent:* éloquent et écolo!
- *casser les coudes:* fait d'énerver les compagnons d'infortune de son interlocuteur.
- *étranpoigner:* étrangler le poignet d'autrui.
- le *maximol:* le maximum pour ne rien faire.
- *docteur pepper:* en étant godlike, faire quelque chose.
- unk *yoüt:* une pomme de terre. Se prononce yo-out
- *yoüt:* qui est n'est pas total. Se prononce yo-ut
- *hadérer:* aimer quelque chose collant. se pronce yadérer.
  + *Ex:* Jean-Miche hadère aux portes.
- *bonc (meilleurc, mieuc):* qui est bon malgré des conséquences négatives.
  En anglais, worth.
- *abodonner:* s'abonner après beaucoup de forcing.

** "Le ciel est" + adj
- *le ciel est laid:* 
    1. refléter la laideur de quelque chose sur quelque chose.
        + *Ex:* Je le ciel est laid un blobfish sur un écran.
    2. voler abev tout sauf des ailes.
        + *Ex:* Un pigeon Le ciel est laid à travers l'espace aérien de la Biavière.

Il est possible de former des vebres en remplaçant laid par n'importe quel ajectif.
Seule la première définition est valable pour ces vebres.

* Lieu
Le DPMI est en effet le Département Provisoire et Momantanément Insolite.

Il se trouve en Biavière.

Et ceci, ad vitam eternam (surtout le provisoire, on y tient vraiment).
